base_url = "https://zurrixxx.github.io/"
title = "CY Bio"
description = "Bio of CY"

compile_sass = true
generate_feed = true

theme = "no-style-please"

taxonomies = [
    { name = "tags" },
    { name = "categories" }
]

[markdown]
highlight_code = true

[extra]
author = "Chao Yang"
logo = "images/logo.png"
# list_pages = true

